# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 05:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_auto_20170204_0519'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topical',
            new_name='Topics',
        ),
    ]
